# Generated by Django 3.2.8 on 2021-11-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
